# Generated by Django 6.0.2 on 2026-03-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_insta', '0003_photo_image_file_alter_photo_image_url_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='follower_profile',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='like',
            name='post',
        ),
        migrations.RemoveField(
            model_name='like',
            name='profile',
        ),
        migrations.AlterField(
            model_name='photo',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='mini_insta/'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
